flowchart LR
    1[(film.yml 数组)] <--> 2[(树 数组)]
    1 --> 3{flag}
    3 -->|包装| 4[Proxy对象\n用来数据是否加载完成]
    查 --> 得
    得 --> 除杂
    除杂 --> 格式化
    格式化 --> 流
    流 --> 分裂
    分裂 --> 查
    分裂 --> 标志
    标志 --> 储存
    储存 --> 打包
    打包 --> 更新视图